### ISSUE TITLE
Add comment in source code that internal material names are case sensitive

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-freiberg-flow-stress#4]
In materials.py the name string is modified and changed into lowercase.

Threrefore the internal name in the source code has to be in lowercase!

There should be a comment in the source code to explain this behavior to the casual user, who migth for instance take this plugin as a template for a user specific flow curve equation implementation.

If uppercase is used for internal material names a hook cannot provide value error.

This issue is also relevant for other plugins for mauk-gottschling-flow-stress.

**Comment by ChRen95** [comment]
Well this is just our implementation.
I would also avoid comments in code since this can be confusing for other (See R. Martins book: "Clean Code"). 
I would suggest we should add a sentence or two to the docs.
